pub const BoxStyles = struct {
    solid_tl: []const u8,
    solid_tr: []const u8,
    solid_bl: []const u8,
    solid_br: []const u8,
    solid_h: []const u8,
    solid_v: []const u8,

    double_tl: []const u8,
    double_tr: []const u8,
    double_bl: []const u8,
    double_br: []const u8,
    double_h: []const u8,
    double_v: []const u8,

    double_single_tl: []const u8,
    double_single_tr: []const u8,
    double_single_bl: []const u8,
    double_single_br: []const u8,
    double_single_h: []const u8,
    double_single_v: []const u8,

    double_single_rounded_tl: []const u8,
    double_single_rounded_tr: []const u8,
    double_single_rounded_bl: []const u8,
    double_single_rounded_br: []const u8,
    double_single_rounded_h: []const u8,
    double_single_rounded_v: []const u8,

    single_thick_tl: []const u8,
    single_thick_tr: []const u8,
    single_thick_bl: []const u8,
    single_thick_br: []const u8,
    single_thick_h: []const u8,
    single_thick_v: []const u8,

    single_double_tl: []const u8,
    single_double_tr: []const u8,
    single_double_bl: []const u8,
    single_double_br: []const u8,
    single_double_h: []const u8,
    single_double_v: []const u8,

    single_double_rounded_tl: []const u8,
    single_double_rounded_tr: []const u8,
    single_double_rounded_bl: []const u8,
    single_double_rounded_br: []const u8,
    single_double_rounded_h: []const u8,
    single_double_rounded_v: []const u8,

    rounded_tl: []const u8,
    rounded_tr: []const u8,
    rounded_bl: []const u8,
    rounded_br: []const u8,
    rounded_h: []const u8,
    rounded_v: []const u8,

    pub fn init(self: *BoxStyles) BoxStyles {
        _ = self;
        return BoxStyles{
            .solid_tl = "┌",
            .solid_tr = "┐",
            .solid_bl = "└",
            .solid_br = "┘",
            .solid_h = "─",
            .solid_v = "│",
            .double_tl = "╔",
            .double_tr = "╗",
            .double_bl = "╚",
            .double_br = "╝",
            .double_h = "═",
            .double_v = "║",
            .double_single_tl = "╓",
            .double_single_tr = "╖",
            .double_single_bl = "╙",
            .double_single_br = "╜",
            .double_single_h = "─",
            .double_single_v = "║",
            .double_single_rounded_tl = "╭",
            .double_single_rounded_tr = "╮",
            .double_single_rounded_bl = "╰",
            .double_single_rounded_br = "╯",
            .double_single_rounded_h = "─",
            .double_single_rounded_v = "║",
            .single_thick_tl = "┏",
            .single_thick_tr = "┓",
            .single_thick_bl = "┗",
            .single_thick_br = "┛",
            .single_thick_h = "━",
            .single_thick_v = "┃",
            .single_double_tl = "╒",
            .single_double_tr = "╕",
            .single_double_bl = "╘",
            .single_double_br = "╛",
            .single_double_h = "═",
            .single_double_v = "│",
            .single_double_rounded_tl = "╭",
            .single_double_rounded_tr = "╮",
            .single_double_rounded_bl = "╰",
            .single_double_rounded_br = "╯",
            .single_double_rounded_h = "═",
            .single_double_rounded_v = "│",
            .rounded_tl = "╭",
            .rounded_tr = "╮",
            .rounded_bl = "╰",
            .rounded_br = "╯",
            .rounded_h = "─",
            .rounded_v = "│",
        };
    }
};
